DROP TABLE Z_AUTH CASCADE CONSTRAINTS;
DROP SEQUENCE Z_AUTH_NO_SEQ;

CREATE TABLE Z_AUTH(
	a_no NUMBER CONSTRAINT a_no_pk PRIMARY KEY,
	a_date DATE CONSTRAINT a_date_nn NOT NULL,
	a_state VARCHAR2(50) CONSTRAINT a_state_nn NOT NULL,
	a_resultN VARCHAR2(1000),
	a_requestN VARCHAR2(1000),
	a_requestP NUMBER,
	j_no NUMBER CONSTRAINT z_a_j_no REFERENCES Z_JOB(j_no) ON DELETE CASCADE
);
CREATE SEQUENCE Z_AUTH_NO_SEQ
	START WITH 1
	INCREMENT BY 1;

INSERT INTO Z_AUTH VALUES(Z_AUTH_NO_SEQ.NEXTVAL, sysdate, '승인완료', '요청합니다.', '승인합니다', 90, 1);
INSERT INTO Z_AUTH VALUES(Z_AUTH_NO_SEQ.NEXTVAL, sysdate, '승인중', '요청해주세요', NULL, 40, 2);
INSERT INTO Z_AUTH VALUES(Z_AUTH_NO_SEQ.NEXTVAL, to_date('2021-03-02', 'YYYY-MM-DD'), '회수', '요청', NULL, 50, 1);
INSERT INTO Z_AUTH VALUES(Z_AUTH_NO_SEQ.NEXTVAL, sysdate, '반려', '', '반려합니다.',70, 1);